server:
  http2:
    enabled: true
  port: 9996
  servlet:
    context-path: /rent-sys-server

logging:
  path: logs
  config: classpath:logback.xml
  level:
    com.netflix.discovery: ERROR

spring:
  aop:
    proxy-target-class: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.18.105:35432/shenxi
    sql-script-encoding: utf-8
    password: cqgcgl
    username: cqgcgl
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/
  cloud:
    inetutils:
      ignored-interfaces:
  redis:
    host: 192.168.18.105
    port: 7001
    password: 123456

management:
  security:
    enabled: false

# 文件上传地址
fileSeverPath: http://file.yolodt.com




