spring:
  profiles:
    active: dev
  application:
    name: rent-sys-server
  jackson:
    serialization:
      write-dates-as-timestamps: true
  sleuth:
    sampler:
      probability: 1
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/com/yolo/hw/user/domain/customer/**/mapper/*.xml
